# Pre-commit configuration for N8N AI Services Platform
repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        files: ^(queue-metrics|dynamic-scaler)/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^(queue-metrics|dynamic-scaler)/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,W503,E501']
        files: ^(queue-metrics|dynamic-scaler)/.*\.py$

  # Docker and YAML formatting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yaml]

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: ['--ignore', 'DL3008', '--ignore', 'DL3009', '--ignore', 'DL3015', '--ignore', 'DL3016']

  # Shell script linting
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        files: ^utils/backup/.*\.sh$
        args: ['-e', 'SC1091', '-e', 'SC2086', '-e', 'SC2012', '-e', 'SC2181', '-e', 'SC1009', '-e', 'SC1078', '-e', 'SC1079', '-e', 'SC1073', '-e', 'SC1072', '-e', 'SC1090', '-e', 'SC2046', '-e', 'SC2129', '-e', 'SC1036']

  # Markdown formatting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: '^(CHANGELOG|README|.*REFERENCE|.*GUIDE|.*REPORT|GETTING_STARTED|utils/).*\.md$'

  # Environment file checks
  - repo: local
    hooks:
      - id: check-env-example
        name: Check .env.example exists
        entry: bash -c 'test -f .env.example || (echo ".env.example file missing!" && exit 1)'
        language: system
        pass_filenames: false
        files: '\.env$'

      - id: check-docker-compose-syntax
        name: Validate Docker Compose files
        entry: docker compose config
        language: system
        pass_filenames: false
        files: 'docker-compose\.ya?ml$'

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: '\.env\.example$'

  # Git commit message formatting
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
