# YAML linting configuration
extends: default

rules:
  line-length: disable

  indentation:
    spaces: 2

  comments:
    min-spaces-from-content: 1

  document-start: disable

  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

ignore: |
  *.yml.j2
  *.yaml.j2
  .github/workflows/*.yml
  docker-compose.gpu.yml
  docker-compose.yml
